import { describe, it, expect } from 'vitest'
import { exports } from 'cloudflare:workers'

const IncomingRequest = Request<unknown, IncomingRequestCfProperties<unknown>>

function openClientWebSocket(res: Response): WebSocket {
  const ws = res.webSocket
  if (!ws) throw new Error('response has no webSocket')
  ws.accept()
  return ws
}

function nextMessage(ws: WebSocket, timeoutMs = 2000): Promise<string> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('timeout waiting for ws message')), timeoutMs)
    ws.addEventListener('message', (e: MessageEvent) => {
      clearTimeout(timer)
      resolve(typeof e.data === 'string' ? e.data : String(e.data))
    }, { once: true })
    ws.addEventListener('error', () => {
      clearTimeout(timer)
      reject(new Error('ws error'))
    }, { once: true })
    ws.addEventListener('close', () => {
      clearTimeout(timer)
      reject(new Error('ws closed before message'))
    }, { once: true })
  })
}

describe('worker fetch entrypoint', () => {
  it('returns 404 for non /socket.io/ paths', async () => {
    const req = new IncomingRequest('https://example.com/other')
    const res = await exports.default.fetch(req)
    expect(res.status).toBe(404)
  })

  it('returns 400 when /socket.io/ request is not a websocket upgrade', async () => {
    const req = new IncomingRequest('https://example.com/socket.io/')
    const res = await exports.default.fetch(req)
    expect(res.status).toBe(400)
    expect(await res.text()).toBe('websocket only')
  })

  it('returns 101 and a websocket for upgrade requests', async () => {
    const req = new IncomingRequest('https://example.com/socket.io/?eio_sid=test-sid-12345', {
      headers: { upgrade: 'websocket' },
    })
    const res = await exports.default.fetch(req)
    expect(res.status).toBe(101)
    expect(res.webSocket).toBeDefined()
    const ws = openClientWebSocket(res)
    ws.close()
  })

  it('delivers an engine.io "open" packet on the upgraded WebSocket', async () => {
    const req = new IncomingRequest('https://example.com/socket.io/?eio_sid=test-sid-67890', {
      headers: { upgrade: 'websocket' },
    })
    const res = await exports.default.fetch(req)
    expect(res.status).toBe(101)
    const ws = openClientWebSocket(res)
    try {
      const openPacket = await nextMessage(ws)
      // engine.io v4 open packet: '0' followed by JSON handshake
      expect(openPacket[0]).toBe('0')
      const handshake = JSON.parse(openPacket.slice(1))
      // sid is generated by the Worker from generateBase64id(), not the URL param
      expect(typeof handshake.sid).toBe('string')
      expect(handshake.sid.length).toBeGreaterThan(10)
      expect(handshake).toHaveProperty('pingInterval')
      expect(handshake).toHaveProperty('pingTimeout')
      // allow the 100ms-delayed createEioSocket + SocketActor wiring to settle
      await new Promise((r) => setTimeout(r, 200))
    } finally {
      ws.close()
    }
  })
})